### ISSUE TITLE
The current state

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#18]
WebRender: https://github.com/szeged/webrender/commits/gfx-wr-4ab9b9b
Servo: https://github.com/szeged/servo/commits/gfx-5d1e027-05-18

Known issues:
- [x] Converting Sampler structures to raw data
- [x] `gfx_glutin` vs `servo_glutin`
- [ ] Handle Resize (window and texture)
- [x] `BGRA`
- [x] `Srgba` for `RGBAF32`
- [x] `Yuv`

1. Converting Sampler structures to raw data
Our previous solution was to convert everything [manually](https://github.com/szeged/webrender/commit/ea4cd3dab1720e3372d7464c34a53ca7213d57b0#diff-d058594280164bb23d9b1ca25ba9fe79L868). Now we do with [slice casting](https://github.com/szeged/webrender/blob/gfx-wr-4ab9b9b/webrender/src/renderer.rs#L167) (except from [gradient](https://github.com/szeged/webrender/blob/gfx-wr-4ab9b9b/webrender/src/renderer.rs#L280), because there is something off (most probably with the length)).

2.  `gfx_glutin` vs `servo_glutin`
The latest version of `gfx-rs` uses `glutin 0.8.0` and this version doesn't contains `WindowProxy` anymore. But `servo-glutin` still uses `WindowProxy` in the compositor.

3. Handle Resize (window and texture)
We don't support any resize yet.

4. `BGRA`
Gradient data comes in bgra format, but the `B8_G8_R8_A8` is not implemented on `OpenGL` backend (There are `TODO`-s for placeholder), so we [swap](https://github.com/szeged/webrender/blob/gfx-wr-4ab9b9b/webrender/src/device.rs#L704) the red and blue bytes before updating the texture. Is there a specific blocker for implementing `B8_G8_R8_A8`? We found a minimal workaround for the use case which we need, but this isn't in the current code yet: https://github.com/zakorgy/gfx/commit/364c47b6487e85049341a3da8d3b7c77ba22510c

5. `Srgba` for `RGBAF32`
Our colors still off because we use `RGBAF32` for our "non-texture" samplers (e.g. `Data16`, `Layer`).
The color values are stored in the data* samplers (at least seems that way) and now the gamma correlation.

6. `Yuv`
The `Yuv` support is not working correctly, we know what seems to be the problem and working on it.

**Comment by dati91** [comment]
@kvark
The relevant code is in [renderer.rs](https://github.com/szeged/webrender/blob/gfx-wr-4ab9b9b/webrender/src/renderer.rs) and [device.rs](https://github.com/szeged/webrender/blob/gfx-wr-4ab9b9b/webrender/src/device.rs).

**Comment by kvark** [comment]
Here is my review:
  1. You can re-implement the bits of `gfx_window_glutin` that you need, in order to use `servo-glutin` instead of `glutin`.
  2. You shouldn't need to import `gfx_core`. The necessary functions and types are re-exported in `gfx`.
  3. Your `out_color` in the PSO declaration is RGBA32F. I think you just need `Rgba8` or `Srgba8` there instead.
  4. `color0`, `color1`, `color2` should not be `Srgba8`. Imagine a YUV texture provided there, we don't want the channels to be gamma-decoded by the texture samplers. Same for `cache_rgba8`. I suggest you to make a good pass and re-evaluate all the used texture formats.
  5. `update_texture_data` looks quite hacky
  6. might want to use `cast_slice` instead of `slice::from_raw_parts`

Finally, there is a lot of code pieces that seem non-idiomatic to rust. I don't think it's critical to fix those, but it would be great if you became more familiar with Rust way of APIs. This link could be a starting point - https://github.com/brson/rust-api-guidelines
    - almost never you really need to have `Vec` or `String` arguments. Instead, slices are appropriate (`&[T]` and `&mut [T]`, also `&str`)
    - containers like vectors and maps can be `collect()`-ed into from iterators (as opposed to creating one `with_capacity`, iterating manually and calling `push`/`insert`).
    - use `From`/`Into` traits for stuff like `PrimitiveInstance` to `Instances` conversion. Similarly, doing `let encoder = Encoder::from(...)` is simpler than `let encoder: Encoder = ....into()`
    - field/items comments should start with `///` and not `//`

Overall, it looks rough but functional. Hopefully, we'll pay more attention to the shape once core logic is in place.

**Comment by kvark** [comment]
> Is there a specific blocker for implementing B8_G8_R8_A8

Not really, just no one bothered to do it yet. Do you want to submit a PR or leaving it for us?

**Comment by zakorgy** [comment]
@kvark  I have sent a PR for this.
