### ISSUE TITLE
Incorrect synchronization when running dromaeo tests in servo

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#186]
left: ours, right: original
![output3](https://user-images.githubusercontent.com/2149430/41414313-f71f53b0-6fe5-11e8-9eca-5509f49a1a70.gif)

Running tests on [dromaeo](http://dromaeo.com/) causes screen flickering, which means we have a synchronization issue.
Also the validation layer shows no error.

**Comment by dati91** [comment]
This issue is only present in the `release` build. With debug, it works fine.

**Comment by kvark** [comment]
I wonder if you can catch it with RenderDoc.

**Comment by zakorgy** [comment]
We captured a flickering image with WR and loaded it in Renderdoc. We found that there are NaN values for the vertex positions in some cases, but otherwise everything else (texture viewer, pipeline state, VS inputs) looked fine.
We think that the missing synchronization of the vertex textures(resource_cache, render_task .. etc) can cause this, because a VS tries to read on of them while an upload is not finished. This is  why we get those NaN values for the vertex positions.
We have to rework the texture synchronization, to handle these special cases properly.
