### ISSUE TITLE
Incorrectly displayed colors

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#19]
The pixel values we receive for textures (color0, cache_rgba8, data16,  data32 ...) are displayed still pale-coloured compared to the expected output. Changing the color format to Srgba8 from Rgba8 in case of `color0`, `color1`, `color2` and `cache_rgba8` made the images display with the correct colors, but for YUV images this causes problems.
Other Textures like `data16`, `data32` ... have  Rgba32F formats, changing these to Srgba8 is not a valid option.
Is there a way to make gfx_rs compute the correct values, instead of touching the shader code or recomputing the pixel values?

**Comment by kvark** [comment]
@zakorgy 

color0 should use `Srgba8` when it's not YUV
YUV should use `R8` (since each texture is single channel), which makes the solution 3) of #20 most appropriate
`cache_rgba8` should use `Rgba8`

For YUV, another option would be to have separate SRV inputs (as `R8`) for YUV, while keeping `color0` (or just `color`) strictly `Srgba8`. In WR, we reached the sampler limit, but gfx-rs re-distributes and allocates texture slots automatically, so having more entry points is not a problem.

**Comment by zakorgy** [comment]
I assume we can ignore the 4. answer from [here]( https://github.com/szeged/webrender/issues/18#issuecomment-302792870) then, when it's not YUV.

**Comment by dati91** [comment]
Our gradient seems a bit off... (with this [test](https://gist.github.com/dati91/23fce9cb7ca4df5778d95016624ef557))
The result: (top: orig, bottom: our)
![grad_1](https://cloud.githubusercontent.com/assets/2149430/26636912/5682f462-461e-11e7-8fe5-ceb3da502960.PNG)


The same test with `0.99` StopGradient instead of `1.0`
![grad_099](https://cloud.githubusercontent.com/assets/2149430/26637025/a442808c-461e-11e7-936d-ba88ffdc8c4b.PNG)

**Comment by zakorgy** [comment]
I tried to make the gamma correction for the AlignedGradient case [here](https://github.com/zakorgy/webrender/commit/cd69a706ef46db335fe3a2ffe3ee15bede6377b0#diff-33603c013bcfbe19d5d30c93a810759aR1351) (first calculating the sRGB values, and after that applying the gamma correction). The test file is the same as above.
The result(bottom img) still differs from the original(top img), due to the negative values from the matrix multiplication:
![original_wr](https://cloud.githubusercontent.com/assets/11725775/26829740/efa91412-4ac6-11e7-9af3-176340efbbb2.png)
![gamma_wr](https://cloud.githubusercontent.com/assets/11725775/26829744/f23577ac-4ac6-11e7-9cf2-5b2773374862.png)

**Comment by zakorgy** [comment]
@kvark here are the Renderdoc capture files:
[gradient_color.zip](https://github.com/szeged/webrender/files/1095161/gradient_color.zip)
And the [test](https://github.com/zakorgy/webrender/commit/eb524667fab6352e52956dac4625215690e90e81) file we used

**Comment by kvark** [comment]
@zakorgy I'm not able to open the captures, unfortunately (RenderDoc crashes), but from looking at the screenshots again it's rather clear that you just need to "linearize" the colors (from [ARB_framebuffer_sRGB](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_framebuffer_sRGB.txt)):
```
            {  cs / 12.92,                 cs <= 0.04045
       cl = {
            {  ((cs + 0.055)/1.055)^2.4,   cs >  0.04045
```

Also, not sure where you got the `transform_matrix` from? YUV <-> RGB needs a transform matrix, but not gamma correction.

**Comment by zakorgy** [comment]
Looks like the source of the issue is, that gfx_rs encodes the color values for the sRGB color space.
This is enabled [here](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L261).
Skipping this call resolves the color problem.

**Comment by kvark** [comment]
@zakorgy this call is correct, don't disable it.
The logic is that we always keep sRGB enabled, and the actual conversion is controlled by the format of render targets only: GL will ignore the flag if the format doesn't specify sRGB in the first place.

**Comment by zakorgy** [comment]
@kvark If I replace the only remaining Srgba8 Texture which is color0, to be an Rgba8, the color is still wrong without disabling the above mentioned line. Our main target has also a `(SurfaceType::R8_G8_B8_A8 ,ChannelType::Unorm)` Format. Or am I missing something else?

**Comment by kvark** [comment]
> Our main target has also a `(SurfaceType::R8_G8_B8_A8, ChannelType::Unorm)` format

Is that intentional? There is rarely a reason to not use gamma-correction for the main target.

Problem is that the windowing system may still return sRGB-enabled target if you ask for non-sRGB one. This could indeed be worked around by flipping the `FRAMEBUFFER_SRGB` switch in gfx-rs. However, that would have to be an exception put it specifically for the main framebuffer (when we detect it to not have sRGB format), since doing so in general case can't simply be correct.

**Comment by zakorgy** [comment]
@kvark Switching the ChannelType between `Unorm` and `Srgb` for the main target, does not changes the output colors.

After your description I came up with the following [workaround](https://gist.github.com/zakorgy/d6e7a642db895c5fa69211e8a6e4cf7e) for the `BindFrameBuffer` command. Only enable GL_FRAMEBUFFER_SRGB if it's supported, and we not using the main framebuffer.

**Comment by zakorgy** [comment]
Also we have tried the triangle example of the gfx crate with (top image) and without (bottom image) `FRAMEBUFFER_SRGB` enabled, and the results are differing: (tested on Intel and Nvidia driver too)
![triangle_default](https://user-images.githubusercontent.com/11725775/27591931-81f13e34-5b53-11e7-8bc9-88dc362cce8b.png)
![triangle_wo_srgb](https://user-images.githubusercontent.com/11725775/27591933-83bbbc94-5b53-11e7-917e-565451665b12.png)
