### ISSUE TITLE
Yuv images

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#20]
In almost every case we receive the bytes for textures in BGRA order, but for Yuv images we receive these in RGBA order. Until now we have used Rgba format for `color0` but using Bgra instead made our code less hacky (we don't need to reverse the red and blue bytes in `update_texture_data`). This modification made our Yuv image colors are displayed wrong. I have the following ideas as a solution:
1. Manually change the red and blue bytes, so move the hacky part to Yuv images.
2. Enable swizzling on OpenGL backend, so we can switch the red and blue channels when creating Textures (This is unimplemented in gfx_rs, and it seems like OpenGL 3.3 feature).
3. Make a different pipeline for Yuv images with different color formats.
4. Extend the existing pipeline with additional `TextureSampler` for `color0`. I tried this, but this approach displayed some random memory content to the screen.

Any advice is welcome.

**Comment by kvark** [comment]
about 3: YUV uses a different shader anyway, so technically you have a separate pipeline. You'd then need to have the texture PSO component to use `RawShaderResource`, so that you can override the format in the `Init` struct. It may be a little inconvenient, so there is also another choice:

5. just do the swizzling in the shader. YUV is a separate shader anyway, and swizzling costs nothing. This is the simplest solution.

**Comment by zakorgy** [comment]
Now, that the yuv shaders are in the [right order](https://github.com/zakorgy/webrender/commit/2a66aee4e518888c9e7b52780d6af6a909d3c91a), it seems the only issue here is the color related one #19 .

**Comment by zakorgy** [comment]
#19 already has a workaround solution, and the yuv shaders are working with it.
