### ISSUE TITLE
Support DX11 backend

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#25]

**Comment by zakorgy** [comment]
We managed to draw the rectangle of the basic example with dx11.
![dx11_rect](https://user-images.githubusercontent.com/11725775/28157504-08893162-67b7-11e7-85de-4217235488c4.PNG)
.

**Comment by zakorgy** [comment]
Until now, we rewrote the OpenGL shaders to hlsl manually.
We managed to generate a hlsl shader with [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) from the ps_rectangle.vert, but the result shader has [some](https://gist.github.com/zakorgy/651b18a8193c069d95219b50b20e476c#file-ps_rect-vert-L259) [lines](https://gist.github.com/zakorgy/651b18a8193c069d95219b50b20e476c#file-ps_rect-vert-L330), with incorrect syntax. Maybe because this conversion path is still experimental in SPIRV-Cross.
After we fix the [shader](https://gist.github.com/zakorgy/6c88aba2640b6cddfb730a1ab34467a5) to compile, gfx panics with an 'attempt to divide by zero' ([backtrace](https://gist.github.com/zakorgy/bcef58417f712ac153e5ee1da3008620#file-backtrace)) at [`backend\dx11\src\mirror.rs:233`](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx11/src/mirror.rs#L233)

**Comment by kvark** [comment]
Thanks for the info! We'll investigate in https://github.com/gfx-rs/gfx/issues/1393

**Comment by zakorgy** [comment]
Finally we managed to work more shaders together (text, border_edge, rectangle).
![multiple_shaders](https://user-images.githubusercontent.com/11725775/28709764-d6ccc568-7381-11e7-85ea-35789735d9c9.PNG)
The source of the problem was this [function](https://github.com/szeged/webrender/blob/dx11/webrender/src/device.rs#L802) which updates a row of the `sResourceCache` texture if there is a dirty row in the `CacheTeture` in [renderer.rs](https://github.com/szeged/webrender/blob/dx11/webrender/src/renderer.rs#L290).
This function works well either with OpenGL backend or if we have only one dirty row in the `CacheTexture` with dx11. If there is more than one dirty row and we use dx11 the subsequent `encoder.upadte_textures` calls update the texture in a very strange way (removes filled data and/or writes in a wrong row), this can be tracked in RenderDoc.
I made a temporary workaround with updating the entire texture when any of the rows in the `CacheTexture` is dirty, this produced the above picture.
@kvark could you verify if we us the wrong parameters int this [function](https://github.com/szeged/webrender/blob/dx11/webrender/src/device.rs#L802), or is this a bug related to the [update_texture](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx11/src/execute.rs#L61) in the dx11 backend of `gfx`?

**Comment by zakorgy** [comment]
We have a screen capture about using our dx11 powered webrender in servo. Unfortunately winit handles the events in a different way than servo-glutin does, so the browser behavior is flacky yet, and we have only 3 shaders (ps_text_run, ps_border_edge, ps_rectangle) working appropriately with dx11 in our webrender .
![dx11_servo](https://user-images.githubusercontent.com/11725775/28878438-9ae5d9dc-779f-11e7-9e4e-d7fb8d7738bd.PNG)
![dx11_servo3](https://user-images.githubusercontent.com/11725775/28878969-2020629c-77a1-11e7-8552-492e162bec52.PNG)

**Comment by kvark** [comment]
@zakorgy 
I was able to reproduce the test (at last) and investigate the cause. Indeed the bug is on our side - https://github.com/gfx-rs/gfx/issues/1418 . You can either continue using the workaround, or actually do the updates via PBO similar to the old GL path (that is commented out), which will be faster.

**Comment by zakorgy** [comment]
Some new gifs with servo running with dx11. The second shows, that we have missing images on the left side.
![servo](https://user-images.githubusercontent.com/11725775/29667380-7a0c95f4-88dc-11e7-90d8-dbb03fb3a2c6.gif)
![reddit](https://user-images.githubusercontent.com/11725775/29668077-3167129a-88df-11e7-92e0-64c351d68aa4.gif)

**Comment by dati91** [comment]
We are trying to add support for Wrench (with dx11).
The `read_pixels` works with [this PR](https://github.com/gfx-rs/gfx/pull/1630).
But if we change the window size, the results get distorted(/shifted?).

This repository can be used to reproduce it: https://github.com/dati91/webrender/tree/dx11_read_pixels
While running an example, pressing the "R" will call `read_pixels` and save it to a png.
The size can be changed here: https://github.com/dati91/webrender/blob/dx11_read_pixels/webrender/examples/common/boilerplate_dx.rs#L90
How we implement read_pixels: https://github.com/dati91/webrender/blob/dx11_read_pixels/webrender/src/device.rs#L771

The original example:
![read_pixels_result_without_size](https://user-images.githubusercontent.com/2149430/33267819-2affa4a8-d37b-11e7-828f-6d733e84d7d5.png)
Same with 1920x1080 size
![read_pixels_result_with_size_150_150](https://user-images.githubusercontent.com/2149430/33267820-2b198abc-d37b-11e7-986e-af8150967c3b.png)
Same with 150x150 size
![read_pixels_result_with_size_1920_1080](https://user-images.githubusercontent.com/2149430/33267821-2b331fd6-d37b-11e7-8de7-46da2c89fef0.png)

The mapping we used to repoduce this is 1:1 (the rect size is the same as the window size), so maybe the problem is in the DX11 call? Or maybe we are doing something wrong.. :/
cc @kvark

**Comment by dati91** [comment]
Some additional finding:
I'm trying to draw this:
```
        let bounds = (0, 0).to(5, 10);
        builder.push_rect(bounds, None, ColorF::new(1.0, 0.0, 0.0, 1.0));
        let bounds = (5, 0).to(10, 10);
        builder.push_rect(bounds, None, ColorF::new(1.0, 1.0, 0.0, 1.0));
```
in a window sized to 10x10

Which will be resized to 120x10, because of the window header. (Name and 3 buttons)

I get the following if i print out the raw data: https://gist.github.com/dati91/2cd8f0ef69fc5c147207869df3352af2

Which looks like this:
![read_pixels_result](https://user-images.githubusercontent.com/2149430/33279613-7329b1b4-d39f-11e7-8233-3c285be64413.png)

The issue which cause the "shifting" is the fact that each line (from the second line) starts with some kind of empty data. 
On the big one (1920x1080 which will be resized to 1916x1080) is 4 pixels.
In the 120x10 example it is 8 pixels.

My main concern is that zeros are appearing on "data" (gist 2. line) which is the result of `factory.map_texture_read` call.

**Comment by dati91** [comment]
Hmmm maybe this causing the problem:
```
before RowPitch=480 DepthPitch=0
// call Map
after RowPitch=512 DepthPitch=5120
```
The 512 is 480 + 8 (missing pixels) * 4 (texel_size)

**Comment by dati91** [comment]
https://stackoverflow.com/questions/37754135/dxgi-format-yuy2-textures-return-different-rowpitch-under-windows-8-1-and-window
So turns out it depends on the driver...
