### ISSUE TITLE
Move to the new gfx-rs swapchain API

### ISSUE THREAD

**Issue by kvark** [szeged/webrender#317]
See https://gfx-rs.github.io/2019/10/01/update.html

Quad example update - https://github.com/gfx-rs/gfx/commit/40a905ff0ccd583f18ced4250c27b7765716a16f#diff-3396f7c6f19ad0882c9d181e08c8c702

**Comment by zakorgy** [comment]
With the new swapchain API we can't access directly the frame images. Steps needs to be done before we can move to the new API:
- [ ] Replace pipeline barriers on frame images with render passes.
- [ ] Make a workaround for blitting from/to frame images. (using shaders?)
- [ ] Rework the read_pixel logic which we use in wrench, because we can't directly read the frame image content into a buffer. Instead we render to a different image which we can read back and copy the result from that image to the screen.

**Comment by kvark** [comment]
More stuff to read about (1) - https://github.com/gpuweb/gpuweb/issues/437

**Comment by zakorgy** [comment]
Fixed in #331
