### ISSUE TITLE
Image clear with scissor.

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#69]
The original [`clear_target`](https://github.com/servo/webrender/blob/master/webrender/src/device.rs#L1899) uses scissors to only clear a part of an image.

Our [`clear_target`](https://github.com/szeged/webrender/blob/master/webrender/src/device.rs#L2906) mimic the same calls, but it won't work, because the `set_scissor` sets a pipeline state and we clearing without a pipeline.

We need to clear outside a pipeline, and afaik https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#clears-outside is the only way, and it is not take any rect params.
(The [`clear_attachments`](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#clears-inside) requires a pipeline but uses rects.)

As a workaround we could use [clear rect shaders](https://github.com/szeged/webrender/blob/WR_53_dx11/webrender/src/renderer.rs#L2511) like last year, or maybe the [`FillBuffer`](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#clears-filling-buffers).
Or an empty shader/pipeline with `clear_attachments`.

**Comment by kvark** [comment]
IIRC, We are only using scissor as optimization for clears anyway. So let's clear everything for now, and then look into a better solution after the correctness is achieved.

**Comment by dati91** [comment]
Yeah, it looks like the scissor calls (not just in the `clear_target`) are an optimization.

**Comment by zakorgy** [comment]
In the `text\ahem.yaml` reftest we have a 96x96 scissor rect [here](https://github.com/servo/webrender/blob/9596f127342e64aea628b3a3ff3917ed398b5e02/webrender/src/renderer.rs#L3328) for optimization. At the moment we don't handle the [scissor part] (https://github.com/szeged/webrender/blob/master/webrender/src/device.rs#L3238) of clears, just clear the entire texture. This is wrong, because the test try to read the cleared data in later draw calls.
As a workaround we can return if we have a scissor (this fixes the above mentioned test), and create a pipeline for the clear with scissor later, if it increases the performance.
