### ISSUE TITLE
Update WebRender regularly

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#9]

**Comment by zakorgy** [comment]
The current state of work can be found here: https://github.com/szeged/webrender/tree/gfx-wr-8516d6.
This works with the following servo version, with a little modification: https://github.com/szeged/servo/commits/gfx-1b9e1c-05-04.
Rectangles and borders are displayed well, images have a blank rectangle in their place and the text is still WIP.

**Comment by zakorgy** [comment]
The current state of work can be found here: https://github.com/szeged/webrender/tree/gfx-wr-005eb3.
This works with the following servo version, with a little modification: https://github.com/szeged/servo/commits/gfx-f7d67b8-05-11.
Images and text are displayed, but they are flaky since the clipping is missing. Gradient display works also.

**Comment by zakorgy** [comment]
Webrender: https://github.com/szeged/webrender/tree/gfx-wr-4ab9b9b
Servo: https://github.com/szeged/servo/tree/gfx-5d1e027-05-18

**Comment by zakorgy** [comment]
Webrender: https://github.com/szeged/webrender/tree/gfx-wr-c003d55-0525
Servo: https://github.com/szeged/servo/tree/gfx-9e7f02b-05-25

**Comment by zakorgy** [comment]
Webrender: https://github.com/szeged/webrender/tree/gfx-wr-29ce31a
Servo: https://github.com/szeged/servo/tree/gfx-2ff781-0629

**Comment by zakorgy** [comment]
Webrender: https://github.com/szeged/webrender/tree/refactor_44_to_50
Servo (GL): https://github.com/szeged/servo/tree/gfx-glutin
Servo (D3D11): https://github.com/szeged/servo/tree/gfx-winit-dx11
